insert into category (id, name, description, image, parent_category_id)
values  (1, 'Электроника', '', null, null),
        (2, 'Смартфоны', '', null, 1),
        (3, 'Планшеты', '', null, 1),
        (4, 'Наушники', '', null, 1),
        (5, 'Одежда', '', null, null),
        (6, 'Брюки', '', null, 5),
        (7, 'Верхняя одежда', '', null, 5),
        (8, 'Шубы', '', null, 7),
        (9, 'Пуховики', '', null, 7),
        (10, 'Книги', '', null, null),
        (11, 'Комиксы', '', null, 10),
        (12, 'Мебель', '', null, null),
        (13, 'Мягкая мебель', '', null, 12),
        (14, 'Другое', '', null, null);